import { piasters } from "./money";
import type { AppState } from "./types";

export const DEMO_PASSWORD = "demo1234";

export const seedState = (): AppState => ({
  currentUserId: null,
  settings: {
    pettyLimitPiasters: piasters(200),
    retentionPct: 5,
  },
  users: [
    {
      id: "u-owner",
      name: "صاحب الشركة",
      email: "owner@demo.siteflow",
      password: DEMO_PASSWORD,
      role: "owner",
      phone: "01000000001",
      projectIds: ["p-maadi", "p-zayed"],
    },
    {
      id: "u-finance",
      name: "سارة — الحسابات",
      email: "finance@demo.siteflow",
      password: DEMO_PASSWORD,
      role: "finance",
      phone: "01000000002",
      projectIds: ["p-maadi", "p-zayed"],
    },
    {
      id: "u-supervisor",
      name: "كريم — المشرف",
      email: "supervisor@demo.siteflow",
      password: DEMO_PASSWORD,
      role: "supervisor",
      phone: "01000000003",
      projectIds: ["p-maadi", "p-zayed"],
    },
    {
      id: "u-engineer",
      name: "أحمد — المهندس",
      email: "engineer@demo.siteflow",
      password: DEMO_PASSWORD,
      role: "engineer",
      phone: "01000000004",
      projectIds: ["p-maadi", "p-zayed"],
    },
    {
      id: "u-client",
      name: "العميل — فيلا زايد",
      email: "client@demo.siteflow",
      password: DEMO_PASSWORD,
      role: "client",
      phone: "01000000005",
      projectIds: ["p-zayed"],
    },
  ],
  projects: [
    {
      id: "p-maadi",
      name: "شقة المعادي",
      location: "المعادي، القاهرة",
      clientName: "عميل المعادي",
    },
    {
      id: "p-zayed",
      name: "فيلا الشيخ زايد",
      location: "الشيخ زايد",
      clientName: "عميل فيلا زايد",
    },
  ],
  advances: [
    {
      id: "a-maadi",
      personUserId: "u-engineer",
      projectId: "p-maadi",
      title: "عهدة تشطيب المعادي",
      disbursedPiasters: piasters(15000),
      status: "active",
      createdAt: "2026-09-01T09:00:00.000Z",
    },
    {
      id: "a-zayed",
      personUserId: "u-engineer",
      projectId: "p-zayed",
      title: "عهدة فيلا زايد",
      disbursedPiasters: piasters(8000),
      status: "active",
      createdAt: "2026-09-04T09:00:00.000Z",
    },
  ],
  captures: [
    {
      id: "c-approved",
      projectId: "p-maadi",
      createdBy: "u-engineer",
      source: "web",
      originalText: "فاتورة سيراميك حمام 3200",
      amountPiasters: piasters(3200),
      vendorName: "معرض السيراميك",
      description: "سيراميك حمام الشقة",
      movementType: "expense",
      pettyNoReceipt: false,
      status: "approved",
      advanceId: "a-maadi",
      supervisorNote: "المشروع والمعرض صحيحان",
      financeNote: "تم الاعتماد",
      returnReason: "",
      createdAt: "2026-09-08T11:00:00.000Z",
    },
    {
      id: "c-supervisor",
      projectId: "p-maadi",
      createdBy: "u-engineer",
      source: "whatsapp",
      originalText: "صرفت 850 دهانات أوضة المعيشة",
      amountPiasters: piasters(850),
      vendorName: "عبد الله للدهانات",
      description: "دهانات أوضة المعيشة",
      movementType: "expense",
      pettyNoReceipt: false,
      status: "with_supervisor",
      advanceId: "a-maadi",
      aiAmount: piasters(850),
      aiVendor: "عبد الله للدهانات",
      supervisorNote: "",
      financeNote: "",
      returnReason: "",
      createdAt: "2026-09-15T08:20:00.000Z",
    },
    {
      id: "c-finance",
      projectId: "p-zayed",
      createdBy: "u-engineer",
      source: "web",
      originalText: "سباكة مطبخ 1400",
      amountPiasters: piasters(1400),
      vendorName: "سباك عماد",
      description: "تأسيس سباكة المطبخ",
      movementType: "expense",
      pettyNoReceipt: false,
      status: "with_finance",
      advanceId: "a-zayed",
      supervisorNote: "على عهدة زايد",
      financeNote: "",
      returnReason: "",
      createdAt: "2026-09-15T10:00:00.000Z",
    },
    {
      id: "c-petty",
      projectId: "p-maadi",
      createdBy: "u-engineer",
      source: "whatsapp",
      originalText: "شاي وغاز للصنايعية 45",
      amountPiasters: piasters(45),
      vendorName: "بقالة الموقع",
      description: "نثريات شاي وغاز",
      movementType: "expense",
      pettyNoReceipt: true,
      status: "draft",
      advanceId: "a-maadi",
      supervisorNote: "",
      financeNote: "",
      returnReason: "",
      createdAt: "2026-09-16T07:40:00.000Z",
    },
  ],
  expenses: [
    {
      id: "e-1",
      captureId: "c-approved",
      advanceId: "a-maadi",
      projectId: "p-maadi",
      amountPiasters: piasters(3200),
      vendorName: "معرض السيراميك",
      description: "سيراميك حمام الشقة",
      pettyNoReceipt: false,
      approvedBy: "u-finance",
      approvedAt: "2026-09-08T15:00:00.000Z",
    },
  ],
  audit: [
    {
      id: "aud-1",
      at: "2026-09-08T15:00:00.000Z",
      actorId: "u-finance",
      action: "اعتماد مصروف",
      entity: "capture",
      entityId: "c-approved",
      before: "with_finance",
      after: "approved",
      source: "finance",
    },
  ],
  boq: [
    {
      id: "b-1",
      projectId: "p-zayed",
      name: "محارة واجهات",
      unit: "متر",
      contractQty: 200,
      unitPricePiasters: piasters(180),
    },
    {
      id: "b-2",
      projectId: "p-zayed",
      name: "دهان داخلي",
      unit: "متر",
      contractQty: 350,
      unitPricePiasters: piasters(90),
    },
    {
      id: "b-3",
      projectId: "p-zayed",
      name: "أرضيات سيراميك",
      unit: "متر",
      contractQty: 120,
      unitPricePiasters: piasters(220),
    },
  ],
  progress: [
    {
      id: "pr-1",
      projectId: "p-zayed",
      boqItemId: "b-1",
      qty: 80,
      note: "واجهات بحرية",
      status: "approved",
      createdAt: "2026-09-10T12:00:00.000Z",
    },
    {
      id: "pr-2",
      projectId: "p-zayed",
      boqItemId: "b-2",
      qty: 40,
      note: "دور أرضي",
      status: "draft",
      createdAt: "2026-09-14T12:00:00.000Z",
    },
  ],
  variations: [
    {
      id: "v-1",
      projectId: "p-zayed",
      boqItemId: "b-1",
      name: "زيادة محارة السور",
      qtyDelta: 20,
      status: "approved",
      createdAt: "2026-09-09T09:00:00.000Z",
    },
    {
      id: "v-2",
      projectId: "p-zayed",
      boqItemId: "b-3",
      name: "تغيير نوع أرضية الصالة",
      qtyDelta: 15,
      status: "pending",
      createdAt: "2026-09-12T09:00:00.000Z",
    },
  ],
  contractAdvances: [
    {
      id: "ca-1",
      projectId: "p-zayed",
      amountPiasters: piasters(50000),
    },
  ],
  clientIpcs: [],
  subcontracts: [
    {
      id: "sc-1",
      projectId: "p-zayed",
      name: "مقاول بياض الباطن",
    },
  ],
  subIpcs: [],
  clientPayments: [
    {
      id: "pay-1",
      projectId: "p-zayed",
      amountPiasters: piasters(50000),
      note: "دفعة مقدمة العقد — ليست عهد المهندس",
      at: "2026-08-20T09:00:00.000Z",
    },
  ],
  portal: {
    "p-zayed": {
      showProgress: true,
      showPhotos: true,
      showIpcs: true,
      showVariations: true,
      showPayments: true,
    },
    "p-maadi": {
      showProgress: false,
      showPhotos: false,
      showIpcs: false,
      showVariations: false,
      showPayments: false,
    },
  },
});
